name: Frontend Build Wrapper

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump'
        required: false
        default: 'none'
        type: choice
        options:
          - none
          - major
          - minor
          - patch
      package_manager:
        description: 'Package manager'
        required: false
        default: 'npm'
        type: choice
        options:
          - npm
          - yarn
          - bun

jobs:
  call-publisher:
    uses: jenesei-software/.github/.github/workflows/frontend_build.yml@main
    with:
      version_type: ${{ inputs.version_type }}
      package_manager: ${{ inputs.package_manager }}
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
